spring:
  config:
    import: optional:file:local.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/spring-auth
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_url: ${KAKAO_REDIRECT_URL}