services:
  my-db-server:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: spring-auth
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
    ports:
      - 3306:3306
volumes:
  mysql_data: