services:
  my-db-server:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: spring-auth
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306